#!/usr/bin/env python3
"""Add ncaahoopR team name aliases."""

import json
from pathlib import Path

ALIASES_FILE = Path(__file__).resolve().parents[2] / "ncaam_historical_data_local" / "backtest_datasets" / "team_aliases_db.json"

# Load existing aliases
with open(ALIASES_FILE, 'r') as f:
    aliases = json.load(f)

print(f"Existing aliases: {len(aliases)}")

# Add ncaahoopR naming conventions
new_aliases = {
    # Abbreviations used by ncaahoopR
    "ucsb": "UC Santa Barbara",
    "loyola mary": "Loyola Marymount",
    "new mexico st": "New Mexico State",
    "sacramento st": "Sacramento State",
    "c. carolina": "Coastal Carolina",
    "washington st": "Washington State",
    "jacksonville st": "Jacksonville State",
    "e michigan": "Eastern Michigan",
    "mt st mary's": "Mount St. Mary's",
    "s carolina st": "South Carolina State",
    "n illinois": "Northern Illinois",
    "n kentucky": "Northern Kentucky",
    "n colorado": "Northern Colorado",
    "n arizona": "Northern Arizona",
    "w michigan": "Western Michigan",
    "w kentucky": "Western Kentucky",
    "w carolina": "Western Carolina",
    "w illinois": "Western Illinois",
    "e kentucky": "Eastern Kentucky",
    "e illinois": "Eastern Illinois",
    "e washington": "Eastern Washington",
    "se missouri st": "Southeast Missouri State",
    "se louisiana": "Southeastern Louisiana",
    "cent arkansas": "Central Arkansas",
    "cent michigan": "Central Michigan",
    "cent conn st": "Central Connecticut State",
    "tenn tech": "Tennessee Tech",
    "tennessee st": "Tennessee State",
    "miss valley st": "Mississippi Valley State",
    "miss st": "Mississippi State",
    "ar-pine bluff": "Arkansas-Pine Bluff",
    "ga southern": "Georgia Southern",
    "nc a&t": "North Carolina A&T",
    "nc central": "North Carolina Central",
    "nc state": "NC State",
    "sf austin": "Stephen F. Austin",
    "pv a&m": "Prairie View A&M",
    "mid tennessee": "Middle Tennessee",
    "g washington": "George Washington",
    "saint joe's": "Saint Joseph's",
    "saint mary's": "Saint Mary's",
    "appalachian st": "Appalachian State",
    "boise state": "Boise State",
    "colorado state": "Colorado State",
    "fresno state": "Fresno State",
    "georgia state": "Georgia State",
    "kent state": "Kent State",
    "penn state": "Penn State",
    "ohio state": "Ohio State",
    "michigan state": "Michigan State",
    "florida state": "Florida State",
    "arizona state": "Arizona State",
    "kansas state": "Kansas State",
    "oklahoma state": "Oklahoma State",
    "oregon state": "Oregon State",
    "utah state": "Utah State",
    "fair dickinson": "Fairleigh Dickinson",
    "st. bonaventure": "St. Bonaventure",
    "st bonaventure": "St. Bonaventure",
    "st. john's": "St. John's",
    "st john's": "St. John's",
    "st. peter's": "St. Peter's",
    "st peter's": "St. Peter's",
    "st. francis (pa)": "St. Francis (PA)",
    "st francis (pa)": "St. Francis (PA)",
    "abil christian": "Abilene Christian",
    "boston u": "Boston University",
    "la tech": "Louisiana Tech",
    "ul monroe": "UL Monroe",
    "umass lowell": "UMass Lowell",
    "liu": "LIU Brooklyn",
    "etsu": "East Tennessee State",
    "ecu": "East Carolina",
    "fau": "Florida Atlantic",
    "fgcu": "Florida Gulf Coast",
    "fiu": "Florida International",
    "ucf": "UCF",
    "unlv": "UNLV",
    "utep": "UTEP",
    "utsa": "UTSA",
    "uva": "Virginia",
    "vcu": "VCU",
    "unc": "North Carolina",
    "unc asheville": "UNC Asheville",
    "unc wilmington": "UNC Wilmington",
    "uncg": "UNC Greensboro",
    "unh": "New Hampshire",
    "uri": "Rhode Island",
    "usf": "South Florida",
    "uic": "UIC",
    "umbc": "UMBC",
    "umkc": "UMKC",
    "njit": "NJIT",
    "siue": "SIU Edwardsville",
    "iupui": "IUPUI",
    "ut arlington": "UT Arlington",
    "ut martin": "UT Martin",
    "ut rio grande": "UT Rio Grande Valley",
    "csu bakersfield": "CSU Bakersfield",
    "csu fullerton": "CSU Fullerton",
    "csu northridge": "CSU Northridge",
    "cal baptist": "California Baptist",
    "cal poly": "Cal Poly",
    "charleston so": "Charleston Southern",
    "jmu": "James Madison",
    "smu": "SMU",
    "tcu": "TCU",
    "byu": "BYU",
    "md-e shore": "Maryland-Eastern Shore",
    "texas a&m-cc": "Texas A&M-Corpus Christi",
    "texas a&m-commerce": "Texas A&M-Commerce",
    "hawai'i": "Hawaii",
    "utah tech": "Utah Tech",
    "utah valley": "Utah Valley",
    "fort wayne": "Purdue Fort Wayne",
    "incarnate word": "UIW",
    "little rock": "Little Rock",
    "long beach state": "Long Beach State",
    "green bay": "Green Bay",
    "queens university": "Queens",
    "north dakota st": "North Dakota State",
    "south dakota st": "South Dakota State",
    "northern iowa": "Northern Iowa",
    "north dakota": "North Dakota",
    "south dakota": "South Dakota",
    "northwestern st": "Northwestern State",
    "north florida": "North Florida",
    "north alabama": "North Alabama",
    "north texas": "North Texas",
    "morehead state": "Morehead State",
    "murray state": "Murray State",
    "austin peay": "Austin Peay",
    "oral roberts": "Oral Roberts",
    "loyola-chicago": "Loyola Chicago",
    "detroit mercy": "Detroit Mercy",
    "bowling green": "Bowling Green",
    "ball state": "Ball State",
    "wright state": "Wright State",
    "youngstown st": "Youngstown State",
    "cleveland state": "Cleveland State",
    "robert morris": "Robert Morris",
    "san jose state": "San Jose State",
    "san diego state": "San Diego State",
    "san diego": "San Diego",
    "san francisco": "San Francisco",
    "santa clara": "Santa Clara",
    "portland state": "Portland State",
    "montana state": "Montana State",
    "weber state": "Weber State",
    "idaho state": "Idaho State",
    "southern utah": "Southern Utah",
    "uc davis": "UC Davis",
    "uc irvine": "UC Irvine",
    "uc riverside": "UC Riverside",
    "uc san diego": "UC San Diego",
    "wichita state": "Wichita State",
    "illinois state": "Illinois State",
    "indiana state": "Indiana State",
    "missouri state": "Missouri State",
    "southern miss": "Southern Miss",
    "southern indiana": "Southern Indiana",
}

added = 0
for key, value in new_aliases.items():
    if key not in aliases:
        aliases[key] = value
        added += 1
        print(f"  Added: {key} -> {value}")

# Save
with open(ALIASES_FILE, 'w') as f:
    json.dump(aliases, f, indent=2, sort_keys=True)

print(f"\nAdded {added} new aliases. Total: {len(aliases)}")
