#!/usr/bin/env python3
"""
Codespace Readiness Check - Python Version
Ensures all dependencies, apps, extensions, and secrets are ready.
Run this to verify the codespace is fully configured.

Usage:
    python scripts/codespaces/ensure_codespace_ready.py

This script:
  1. Verifies Python virtual environment
  2. Installs all Python dependencies
  3. Checks database connectivity
  4. Validates environment configuration
  5. Reports system diagnostics
"""

import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path("/workspaces/green_bier_sports_ncaam_model")
VENV_PATH = PROJECT_ROOT / ".venv"
ENV_FILE = PROJECT_ROOT / ".env.local"

# Color codes
GREEN = "\033[0;32m"
YELLOW = "\033[1;33m"
RED = "\033[0;31m"
BLUE = "\033[0;34m"
NC = "\033[0m"  # No Color


def print_section(title: str) -> None:
    """Print a formatted section header."""
    print(f"\n{BLUE}{'━' * 60}{NC}")
    print(f"{BLUE}{title}{NC}")
    print(f"{BLUE}{'━' * 60}{NC}")


def print_success(msg: str) -> None:
    """Print success message."""
    print(f"{GREEN}✓{NC} {msg}")


def print_warning(msg: str) -> None:
    """Print warning message."""
    print(f"{YELLOW}⚠{NC} {msg}")


def print_error(msg: str) -> None:
    """Print error message."""
    print(f"{RED}✗{NC} {msg}")


def run_command(cmd: list, quiet: bool = False) -> tuple[bool, str]:
    """Execute a shell command and return success status and output."""
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=False,
            cwd=PROJECT_ROOT,
        )
        return result.returncode == 0, result.stdout.strip() + result.stderr.strip()
    except Exception as e:
        return False, str(e)


def check_venv() -> bool:
    """Check and create Python virtual environment if needed."""
    print_section("🐍 Python Virtual Environment")

    if VENV_PATH.exists() and (VENV_PATH / "bin" / "activate").exists():
        print_success("Virtual environment found")

        python_exe = VENV_PATH / "bin" / "python"
        if python_exe.exists():
            success, output = run_command([str(python_exe), "--version"])
            if success:
                print_success(f"Python venv is healthy ({output})")
                return True
            print_warning("Venv Python broken, recreating...")
        else:
            print_warning("Python executable not found in venv")

    print("Creating Python virtual environment...")
    success, output = run_command(["python", "-m", "venv", str(VENV_PATH)])
    if success:
        print_success("Virtual environment created")
        return True
    print_error(f"Failed to create venv: {output}")
    return False


def install_python_deps() -> bool:
    """Install Python dependencies."""
    print_section("📦 Python Dependencies")

    pip_exe = VENV_PATH / "bin" / "pip"

    if not pip_exe.exists():
        print_error("pip not found in venv")
        return False

    # Upgrade pip
    print("Upgrading pip, setuptools, and wheel...")
    run_command([str(pip_exe), "install", "--quiet", "--upgrade", "pip", "setuptools", "wheel"])

    # Production dependencies
    req_file = PROJECT_ROOT / "services" / "prediction-service-python" / "requirements.txt"
    if req_file.exists():
        print("Installing production dependencies...")
        success, output = run_command([str(pip_exe), "install", "-q", "-r", str(req_file)])
        if success:
            print_success("Production dependencies installed")
        else:
            print_warning(f"Some production dependencies failed: {output[:100]}")
    else:
        print_warning(f"Production requirements file not found: {req_file}")

    # Dev dependencies
    dev_req = PROJECT_ROOT / "requirements-dev.txt"
    if dev_req.exists():
        print("Installing development dependencies...")
        success, output = run_command([str(pip_exe), "install", "-q", "-r", str(dev_req)])
        if success:
            print_success("Development dependencies installed")
        else:
            print_warning(f"Some dev dependencies failed: {output[:100]}")

    return True


def check_env_file() -> None:
    """Create or verify .env.local file."""
    print_section("⚙️  Environment Configuration")

    if not ENV_FILE.exists():
        print("Creating .env.local...")
        ENV_FILE.write_text(
            """# Codespaces Auto-Configuration
# Generated by ensure_codespace_ready.py

# Database
DATABASE_URL=postgresql://postgres:postgres@localhost:5432/ncaam_local

# Redis (set either REDIS_URL or host/port/db; docker-compose may use *_FILE)
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_DB=0
# REDIS_URL=redis://localhost:6379/0
# REDIS_PASSWORD_FILE=/run/secrets/redis_password

# Environment
ENVIRONMENT=codespaces
DEBUG=true
LOG_LEVEL=DEBUG

# API Server
API_PORT=8000

# API Keys (must be provided - get from https://the-odds-api.com/)
# Either name is accepted; prefer ODDS_API_KEY
ODDS_API_KEY=
THE_ODDS_API_KEY=

# Optional Webhooks
TEAMS_WEBHOOK_SECRET=

# Azure (optional)
AZURE_SUBSCRIPTION_ID=
AZURE_RESOURCE_GROUP=
AZURE_COSMOS_DB_ENDPOINT=

# Other
PYTHONUNBUFFERED=1
"""
        )
        print_success(".env.local created")
    else:
        print_success(".env.local already exists")

        # Check for critical keys
        content = ENV_FILE.read_text()
        if "ODDS_API_KEY" not in content and "THE_ODDS_API_KEY" not in content:
            print_warning(
                "Neither ODDS_API_KEY nor THE_ODDS_API_KEY found in .env.local - adding..."
            )
            ENV_FILE.write_text(content + "\nODDS_API_KEY=\nTHE_ODDS_API_KEY=\n")


def check_critical_files() -> None:
    """Verify critical project files exist."""
    print_section("📋 Critical Files")

    critical_files = [
        "services/prediction-service-python/app/main.py",
        "services/prediction-service-python/requirements.txt",
        "pyproject.toml",
        "requirements-dev.txt",
        "README.md",
    ]

    for file in critical_files:
        path = PROJECT_ROOT / file
        if path.exists():
            print_success(file)
        else:
            print_error(f"{file} (MISSING)")


def check_system_info() -> None:
    """Print system diagnostic information."""
    print_section("🔍 System Information")

    # Python
    python_exe = VENV_PATH / "bin" / "python"
    if python_exe.exists():
        success, version = run_command([str(python_exe), "--version"])
        print(f"  Python: {version}")

    # pip
    pip_exe = VENV_PATH / "bin" / "pip"
    if pip_exe.exists():
        success, version = run_command([str(pip_exe), "--version"])
        print(f"  Pip: {version}")

    # Go
    success, version = run_command(["go", "version"])
    if success:
        print(f"  Go: {version}")

    # Node
    success, version = run_command(["node", "--version"])
    if success:
        print(f"  Node: {version}")
    else:
        print("  Node: not installed")

    # Docker
    success, version = run_command(["docker", "--version"])
    if success:
        print(f"  Docker: {version}")
    else:
        print("  Docker: not available")

    # Git
    success, version = run_command(["git", "--version"])
    if success:
        print(f"  Git: {version}")


def print_summary() -> None:
    """Print final summary."""
    print(f"\n{BLUE}{'╔' + '═' * 58 + '╗'}{NC}")
    print(f"{BLUE}║{NC}{GREEN}  ✓ Codespace Ready!{NC}{BLUE}" + " " * 39 + f"{BLUE}║{NC}")
    print(f"{BLUE}{'╚' + '═' * 58 + '╝'}{NC}")

    print("\n📝 TODO BEFORE RUNNING:")
    print("  1. Add your ODDS_API_KEY (or THE_ODDS_API_KEY) to .env.local")
    print("    Get it from: https://the-odds-api.com/api-keys")

    print("\n🚀 QUICK START:")
    print(
        "  • API Server: cd services/prediction-service-python && python -m uvicorn app.main:app --reload --port 8000"
    )
    print("  • API Docs:   http://localhost:8000/docs")
    print("  • Tests:      pytest testing/ -v")
    print("  • Lint:       ruff check .")
    print("  • Format:     ruff format .")

    print("\n💡 Re-run this script anytime to ensure everything is ready:")
    print("  python ensure_codespace_ready.py")
    print()


def main() -> int:
    """Main execution."""
    print(f"\n{BLUE}{'╔' + '═' * 58 + '╗'}{NC}")
    print(f"{BLUE}║  NCAAM Codespace Readiness Check{NC}" + " " * 24 + f"{BLUE}║{NC}")
    print(f"{BLUE}{'╚' + '═' * 58 + '╝'}{NC}")

    try:
        # Check and create venv
        if not check_venv():
            return 1

        # Install dependencies
        if not install_python_deps():
            print_warning("Some dependencies may not have been installed")

        # Check environment
        check_env_file()

        # Verify critical files
        check_critical_files()

        # System info
        check_system_info()

        # Print summary
        print_summary()

        return 0

    except Exception as e:
        print_error(f"Unexpected error: {e}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
