"""
Non-D1 Team Filter.

Explicitly blocks D2, D3, NAIA, NCCAA, and other non-D1 teams
from being matched or predicted. This prevents:
1. Fuzzy matching to wrong D1 teams
2. Including games that don't have reliable ratings
3. Degrading model quality with non-D1 game dynamics

A team should be skipped if:
1. It's in the explicit NON_D1_TEAMS blocklist
2. It has no Barttorvik ratings (Barttorvik is D1-only)
3. The game has no market odds (can't bet on it anyway)
"""

from typing import Optional, Set
import re

# Teams explicitly known to be non-D1
# This list is curated from games that appeared in historical data
# Format: lowercase team names or patterns
NON_D1_TEAMS: Set[str] = {
    # ═══════════════════════════════════════════════════════════════════════════
    # NAIA Schools
    # ═══════════════════════════════════════════════════════════════════════════
    "midland university",
    "midland",
    "spalding",
    "spalding pelicans",
    "peru state",
    "peru state bobcats",
    "mayville st",
    "mayville state",
    "mayville st comets",
    "crown college",
    "crown college polars",
    "florida national",
    "florida national conquistadors",
    "jessup university",
    "jessup university warriors",
    "william jessup",
    "kansas christian",
    "north american stallions",
    "north american",
    "oklahoma wesleyan",
    "john brown",
    "john brown golden eagles",
    "science & arts",
    "science and arts",
    "usao",
    "southwestern assemblies",
    "southwestern assemblies of god",
    "wayland baptist",
    "texas wesleyan",
    "st. thomas (tx)",
    "st thomas tx",
    "langston",
    "langston lions",
    "lubbock christian",
    "jarvis christian",
    "huston-tillotson",
    "paul quinn",
    "lyon college",
    "philander smith",
    "stillman",
    "stillman tigers",
    "talladega",
    "talladega tornadoes",
    "selma",
    "selma saints",
    "faulkner",
    "faulkner eagles",
    "mobile",
    "university of mobile",
    "spring hill",
    "spring hill badgers",
    "loyola (la)",
    "loyola new orleans",
    "dillard",
    "dillard bleu devils",
    "xavier (la)",
    "xavier louisiana",
    "lemoyne-owen",
    "lane",
    "lane dragons",
    "covenant",
    "covenant college",
    "reinhardt",
    "reinhardt eagles",
    "thomas more",
    "campbellsville",
    "campbellsville tigers",
    "lindsey wilson",
    "lindsey wilson blue raiders",
    "cumberland (tn)",
    "cumberland tennessee",
    "freed-hardeman",
    "martin methodist",
    "bethel (tn)",
    "bethel tennessee",
    "union (ky)",
    "union kentucky",
    "pikeville",
    "university of pikeville",
    "alice lloyd",
    "berea",
    "berea mountaineers",
    "midway",
    "midway eagles",
    "brescia",
    "brescia bearcats",
    "indiana wesleyan",
    "indiana tech",
    "indiana tech warriors",
    "grace college",
    "grace lancers",
    "goshen",
    "goshen maple leafs",
    "huntington",
    "huntington foresters",
    "bethel (in)",
    "bethel indiana",
    "marian (in)",
    "marian indiana",
    "st. francis (in)",
    "st francis indiana",
    "taylor",
    "taylor trojans",
    "trine",
    "trine thunder",
    "spring arbor",
    "spring arbor cougars",
    "cornerstone",
    "cornerstone golden eagles",
    "madonna",
    "madonna crusaders",
    "siena heights",
    "siena heights saints",
    "concordia (mi)",
    "concordia michigan",
    "davenport",
    "davenport panthers",
    "aquinas",
    "aquinas saints",
    "lawrence tech",
    "rochester (mi)",
    "rochester michigan",
    "malone",
    "malone pioneers",
    "notre dame (oh)",
    "notre dame ohio",
    "walsh",
    "walsh cavaliers",
    "cedarville",
    "cedarville yellow jackets",
    "ohio christian",
    "ohio dominican",
    "ohio dominican panthers",
    "shawnee state",
    "shawnee state bears",
    "rio grande",
    "rio grande redstorm",
    "point park",
    "point park pioneers",
    "carlow",
    "carlow celtics",
    "geneva",
    "geneva golden tornadoes",
    "westminster (pa)",
    "westminster pennsylvania",
    "davis & elkins",
    "davis and elkins",
    "alderson broaddus",
    "alderson-broaddus",
    "bluefield state",
    "bluefield college",
    "concord",
    "concord mountain lions",
    "university of charleston",
    "charleston (wv)",
    "glenville state",
    "glenville state pioneers",
    "wheeling",
    "wheeling cardinals",
    "salem international",
    "ohio valley",
    "ohio valley fighting scots",
    "lindsey wilson blue raiders",
    "west virginia tech",
    "west virginia state",
    "wv state",
    "wv wesleyan",
    "west virginia wesleyan",
    "fairmont state",
    "shepherd",
    "shepherd rams",
    "california (pa)",
    "california pennsylvania",
    "edinboro",
    "edinboro fighting scots",
    "clarion",
    "clarion golden eagles",
    "slippery rock",
    "slippery rock rock",
    "mercyhurst",
    "mercyhurst lakers",
    "gannon",
    "gannon golden knights",
    "lock haven",
    "lock haven bald eagles",
    "bloomsburg",
    "bloomsburg huskies",
    "millersville",
    "millersville marauders",
    "kutztown",
    "kutztown golden bears",
    "east stroudsburg",
    "east stroudsburg warriors",
    "shippensburg",
    "shippensburg raiders",
    "west chester",
    "west chester golden rams",
    "cheyney",
    "cheyney wolves",
    "lincoln (pa)",
    "lincoln pennsylvania",
    "mansfield",
    "mansfield mounties",
    "seton hill",
    "seton hill griffins",
    "pitt-johnstown",
    "pitt johnstown",
    "iup",
    "indiana (pa)",
    "indiana pennsylvania",

    # ═══════════════════════════════════════════════════════════════════════════
    # D2 Schools
    # ═══════════════════════════════════════════════════════════════════════════
    "lenoir-rhyne",
    "lenoir rhyne",
    "lenoir-rhyne bears",
    "kentucky wesleyan",
    "kentucky wesleyan panthers",
    "central state",
    "central state (oh)",
    "central state marauders",
    "urbana",
    "urbana blue knights",
    "fort lauderdale",
    "keiser",
    "keiser seahawks",
    "barry",
    "barry buccaneers",
    "lynn",
    "lynn fighting knights",
    "nova southeastern",
    "nova southeastern sharks",
    "florida southern",
    "florida southern mocs",
    "eckerd",
    "eckerd tritons",
    "rollins",
    "rollins tars",
    "tampa",
    "tampa spartans",
    "saint leo",
    "saint leo lions",
    "palm beach atlantic",
    "pba sailfish",
    "flagler",
    "flagler saints",
    "embry-riddle",
    "embry riddle",
    "embry-riddle eagles",
    "west florida",
    "west florida argonauts",
    "montevallo",
    "montevallo falcons",
    "west georgia",
    "west georgia wolves",
    "valdosta state",
    "valdosta state blazers",
    "albany state",
    "albany state golden rams",
    "fort valley state",
    "fort valley state wildcats",
    "savannah state",
    "savannah state tigers",
    "augusta",
    "augusta jaguars",
    "columbus state",
    "columbus state cougars",
    "georgia southwestern",
    "georgia southwestern hurricanes",
    "clayton state",
    "clayton state lakers",
    "young harris",
    "young harris mountain lions",
    "shorter",
    "shorter hawks",
    "clark atlanta",
    "clark atlanta panthers",
    "morehouse",
    "morehouse maroon tigers",
    "paine",
    "paine lions",
    "miles",
    "miles golden bears",
    "tuskegee",
    "tuskegee golden tigers",
    "spring hill",
    "spring hill badgers",
    "union (tn)",
    "union tennessee",
    "christian brothers",
    "christian brothers buccaneers",
    "delta state",
    "delta state statesmen",
    "mississippi college",
    "mississippi college choctaws",
    "belhaven",
    "belhaven blazers",
    "blue mountain",
    "blue mountain toppers",
    "william carey",
    "william carey crusaders",
    "ouachita baptist",
    "ouachita baptist tigers",
    "henderson state",
    "henderson state reddies",
    "arkansas tech",
    "arkansas tech wonder boys",
    "arkansas-monticello",
    "arkansas monticello",
    "southern arkansas",
    "southern arkansas muleriders",
    "harding",
    "harding bisons",

    # ═══════════════════════════════════════════════════════════════════════════
    # D3 Schools
    # ═══════════════════════════════════════════════════════════════════════════
    "manchester",
    "manchester spartans",
    "ferrum",
    "ferrum panthers",
    "southwestern (tx)",
    "southwestern texas",
    "southwestern pirates",
    "letourneau",
    "letourneau yellow jackets",
    "christendom",
    "christendom crusaders",
    "linfield",
    "linfield wildcats",
    "john jay",
    "john jay bloodhounds",
    "rivier",
    "rivier raiders",
    "hendrix",
    "hendrix college",
    "hendrix warriors",
    "st. andrews",
    "st andrews",
    "st. andrews knights",
    "hiwassee",
    "hiwassee tigers",
    "maine-fort kent",
    "maine fort kent",
    "maine-fort kent bengals",
    "suny-canton",
    "suny canton",
    "canton roos",
    "mid-atlantic christian",
    "mid atlantic christian",
    "mid-atlantic christian mustangs",
    "earlham",
    "earlham college",
    "earlham quakers",

    # ═══════════════════════════════════════════════════════════════════════════
    # NCCAA/Other Non-D1
    # ═══════════════════════════════════════════════════════════════════════════
    "trinity christian",
    "trinity christian trolls",
    "emmanuel (ga)",
    "emmanuel georgia",
    "southeastern (fl)",
    "southeastern florida",
    "palm beach atlantic",
    "the master's",
    "masters",
    "master's university",
    "hope international",
    "vanguard",
    "vanguard lions",
    "william penn",
    "william penn statesmen",
    "mount vernon nazarene",
    "mount vernon nazarene cougars",
    "roberts wesleyan",
    "roberts wesleyan redhawks",
    "nyack",
    "nyack warriors",
    "eastern nazarene",
    "eastern nazarene lions",
    "gordon",
    "gordon fighting scots",
    "johnson & wales",
    "johnson and wales",
    "johnson university",
    "johnson university royals",
    "mid-continent",
    "mid continent",
    "mid-america christian",
    "mid america christian",
    "macu evangels",
    "southwestern christian",
    "southwestern christian eagles",
    "family of faith",
    "oklahoma panhandle",
    "oklahoma panhandle state",
    "panhandle state aggies",
    "bacone",
    "bacone warriors",
    "ecclesia",
    "ecclesia royals",
    "crowley's ridge",
    "crowleys ridge",
    "ozark christian",
    "central christian",
    "central christian saints",
    "baptist bible",
    "faith baptist",
    "bob jones",
    "bob jones bruins",
    "pensacola christian",
    "pensacola christian eagles",
    "clearwater christian",
    "southeastern baptist",
    "florida college",
    "florida college falcons",
    "trinity baptist",
    "trinity baptist eagles",
    "warner",
    "warner royals",
    "webber international",
    "webber warriors",

    # ═══════════════════════════════════════════════════════════════════════════
    # Additional Non-D1 Teams from Backtest (2026-01-05)
    # ═══════════════════════════════════════════════════════════════════════════
    "our lady of the lake",
    "our lady of the lake saints",
    "carver college",
    "carver college cougars",
    "southern virginia",
    "southern virginia knights",
    "regent",
    "regent royals",
    "chaminade",
    "chaminade silverswords",
    "cairn university",
    "cairn university highlanders",
    "cal maritime",
    "cal maritime keelhaulers",
    "bethesda university",
    "bethesda university flames",
    "eureka",
    "eureka red devils",
    "eastern oregon",
    "eastern oregon mountaineers",
    "stanislaus state",
    "stanislaus state warriors",
    "virginia-lynchburg",
    "virginia-lynchburg dragons",
    "arlington baptist",
    "arlington baptist patriots",
    "thomas (me)",
    "thomas me",
    "thomas (me) terriers",
    "emmanuel (ma)",
    "emmanuel (ma) lions",
    "washburn",
    "washburn ichabods",
    "olivet",
    "olivet comets",
    "mcmurry",
    "mcmurry war hawks",
    "transylvania",
    "transylvania pioneers",
    "st. francis brooklyn",
    "st. francis brooklyn terriers",
    "lancaster bible",
    "lancaster bible college",
    "lancasater bible college chargers",
    "warren wilson",
    "warren wilson owls",
    "oakwood",
    "oakwood ambassadors",
    "alliance university",
    "alliance university warriors",
    "keene st",
    "keene st owls",
    "lagrange",
    "lagrange panthers",
    "dallas christian",
    "dallas christian crusaders",
    "immaculata",
    "immaculata mighty macs",
    "rochester university (mi)",
    "rochester university (mi) warriors",
    "rockford",
    "rockford regents",
    "district of columbia",
    "district of columbia firebirds",
    "pittsburgh - greensburg",
    "pittsburgh - greensburg bobcats",
    "pitt-greensburg",
    "piedmont",
    "piedmont lions",
    "mercy",
    "mercy mavericks",
    "missouri s&t",
    "missouri s&t miners",
    "western colorado",
    "western colorado mountaineers",
    "cincinnati clermont",
    "cincinnati clermont cougars",
    "brevard",
    "brevard tornados",
    "college of new jersey",
    "college of new jersey lions",
    "bryn athyn",
    "bryn athyn lions",
    "st. francis (il)",
    "st. francis (il) fighting saints",
    "cardinal stritch",
    "cardinal stritch wolves",
    "kentucky state",
    "kentucky state thorobreds",
    "trinity college of jacksonville",
    "trinity college of jacksonville eagles",
    "massachusetts college of liberal arts",
    "massachusetts college of liberal arts mohawks",
    "fdu florham",
    "fdu florham devils",
    "southern-new orleans",
    "southern-new orleans knights",
    "st. mary's (md)",
    "st. mary's (md) seahawks",
    "colorado christian",
    "colorado christian cougars",
    "westcliff",
    "westcliff warriors",
    "occidental",
    "occidental tigers",
    "antelope valley",
    "fairmont st",
    "fairmont st falcons",
    "cal state la",
    "cal state la golden eagles",
    "san diego christian",
    "san diego christian hawks",
    "keystone",
    "keystone giants",
    "rust",
    "rust bearcats",
    "colby-sawyer",
    "colby-sawyer chargers",
    "csu pueblo",
    "csu pueblo thunderwolves",
    "defiance",
    "defiance yellow jackets",
    "bluefield university",
    "bluefield university ramblin' rams",
    "calumet",
    "calumet crimson wave",
    "adams state",
    "adams state grizzlies",
    "north greenville",
    "north greenville crusaders",
    "tabor",
    "la sierra",
    "la sierra golden eagles",
    "columbia international",
    "columbia international rams",
    "sarah lawrence",
    "sarah lawrence gryphons",
    "lincoln university (ca)",
    "lincoln university (ca) oaklanders",
    "willamette",
    "willamette bearcats",
    "unt dallas",
    "unt dallas trailblazers",
    "southwestern adventist",
    "southwestern adventist knights",
    "schreiner",
    "schreiner mountaineers",
    "northern new mexico",
    "northern new mexico eagles",
    "washington adventist",
    "washington adventist shock",
    "nicholls state colonels",  # Fix: already added with different casing
    "mcneese state cowboys",    # Fix: already added with different casing

    # ═══════════════════════════════════════════════════════════════════════════
    # Additional Non-D1 Teams (Round 2 - 2026-01-05)
    # ═══════════════════════════════════════════════════════════════════════════
    "champion christian",
    "champion christian tigers",
    "truett-mcconnell",
    "truett-mcconnell bears",
    "wisconsin-stout",
    "wisconsin-stout blue devils",
    "east-west university",
    "east-west university phantoms",
    "dakota wesleyan",
    "dakota wesleyan tigers",
    "montana-western",
    "montana-western bulldogs",
    "presentation college",
    "presentation college saints",
    "rogers state",
    "rogers state hillcats",
    "pacific lutheran",
    "pacific lutheran lutes",
    "yellowstone christian",
    "yellowstone christian college centurions",
    "moravian",
    "moravian greyhounds",
    "erskine",
    "erskine flying fleet",
    "merchant marine academy",
    "merchant marine academy mariners",
    "nelson",
    "nelson lions",
    "puget sound",
    "puget sound loggers",
    "lyon",
    "lyon scots",
    "dakota state",
    "dakota state trojans",
    "university of saint katherine",
    "saint katherine",
    "william woods",
    "william woods owls",
    "montana state-northern",
    "montana state-northern lights",
    "northwest indian",
    "northwest indian redhawks",
    "allen university",
    "allen university yellow jackets",
    "anderson (sc)",
    "anderson (sc) trojans",
    "westmont",
    "westmont warriors",
    "life pacific",
    "life pacific warriors",
    "penn state-alleghany",
    "penn state-alleghany nittany lions",
    "texas lutheran",
    "texas lutheran bulldogs",
    "houghton",
    "houghton highlanders",
    "toccoa falls",
    "toccoa falls eagles",
    "whittier",
    "whittier poets",
    "milligan",
    "milligan buffaloes",
    "franciscan university",
    "franciscan university barons",
    "chadron state",
    "chadron state eagles",

    # ═══════════════════════════════════════════════════════════════════════════
    # Additional Non-D1 Teams (Round 3 - 2026-01-05)
    # ═══════════════════════════════════════════════════════════════════════════
    "cornell college (ia)",
    "cornell college (ia) rams",
    "benedictine (az)",
    "benedictine (az) redhawks",
    "north park",
    "north park vikings",
    "howard payne",
    "howard payne yellow jackets",
    "portland bible",
    "portland bible arrows",
    "elmira",
    "elmira soaring eagles",
}

# Patterns that indicate non-D1 status
NON_D1_PATTERNS = [
    r"college\s+(of\s+)?(?!charleston|william\s+&\s+mary|holy\s+cross)",  # "X College" usually D3/NAIA, but exceptions
    r"bible\s+(college|university)",
    r"christian\s+college",
    r"nazarene\s+university",
    r"wesleyan\s+(college|university)",  # except Ohio Wesleyan (D3)
    r"faith\s+",
    r"grace\s+",
    r"\btech\b(?!\s*(a&m|red\s*raiders))",  # "Tech" schools except Texas Tech, but be careful
]


def is_non_d1_team(team_name: str) -> bool:
    """
    Check if a team is non-D1 and should be skipped.

    Args:
        team_name: Raw team name from any source

    Returns:
        True if the team is non-D1 and should be skipped
    """
    if not team_name:
        return False

    lower = team_name.lower().strip()

    # Check explicit blocklist
    if lower in NON_D1_TEAMS:
        return True

    # Check for partial matches in blocklist
    for blocked in NON_D1_TEAMS:
        if blocked in lower or lower in blocked:
            return True

    # Note: We're NOT using pattern matching here because it's too risky
    # to accidentally block D1 teams. Only use explicit blocklist.

    return False


def get_skip_reason(team_name: str) -> Optional[str]:
    """
    Get the reason why a team should be skipped.

    Returns None if the team should NOT be skipped.
    """
    if is_non_d1_team(team_name):
        return f"non_d1_team: {team_name}"
    return None


# NOTE: All D1 aliases are now in team_aliases.json (single source of truth)
# This file ONLY contains the non-D1 blocklist


if __name__ == "__main__":
    # Test the filter
    print("Testing Non-D1 Filter")
    print("=" * 50)

    test_d1 = [
        "Duke Blue Devils",
        "Kentucky Wildcats",
        "Eastern Illinois Panthers",
        "North Dakota State Bison",
    ]

    test_non_d1 = [
        "Spalding Pelicans",
        "Midland University",
        "Ferrum Panthers",
        "Christendom Crusaders",
        "Kentucky Wesleyan Panthers",
        "Lenoir-Rhyne Bears",
    ]

    print("\nShould NOT be blocked (D1):")
    for team in test_d1:
        blocked = is_non_d1_team(team)
        status = "BLOCKED" if blocked else "OK"
        print(f"  {status}: {team}")

    print("\nShould be blocked (Non-D1):")
    for team in test_non_d1:
        blocked = is_non_d1_team(team)
        status = "BLOCKED" if blocked else "MISSED"
        print(f"  {status}: {team}")
